import { useState, useCallback, memo } from "react"
import { Button } from "@/components/ui/button"
import { X } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"
import MarkdownRenderer from "@/components/ui/markdown-renderer"

const DISCLAIMER = `
This content is generated by an artificial intelligence. While we strive for accuracy, the AI may occasionally produce incorrect or biased information. 

**Important Notes:**
- Please verify critical information.
- The AI does not have real-time access to personal data unless shared in this session.
- Responses are based on training data and specific portfolio context.

By using this chatbot, you agree to our terms of service regarding AI-generated content.
`

interface FooterProps {
    disclaimer?: string
    subtitle?: string
}

interface DisclaimerModalProps {
    disclaimer: string
    onClose: () => void
}

const DisclaimerModal = memo(({ disclaimer, onClose }: DisclaimerModalProps) => (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
        <motion.div
            className="absolute inset-0 bg-background/80 backdrop-blur-sm"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
        />

        <motion.div
            className="relative z-[70] w-full max-w-md rounded-xl border bg-background p-6 shadow-2xl"
            initial={{ opacity: 0, scale: 0.95, y: 12 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 12 }}
            role="dialog"
            aria-modal="true"
        >
            <header className="mb-4 flex items-center justify-between border-b pb-2">
                <h2 className="text-lg font-bold">
                    Disclaimer
                </h2>
                <Button
                    variant="ghost"
                    size="icon"
                    onClick={onClose}
                    aria-label="Close dialog"
                >
                    <X />
                </Button>
            </header>

            <div className="max-h-[60vh] overflow-y-auto pr-2 custom-scrollbar text-sm">
                <MarkdownRenderer>{disclaimer}</MarkdownRenderer>
            </div>

            <footer className="mt-6 flex justify-end">
                <Button onClick={onClose}>Understood</Button>
            </footer>
        </motion.div>
    </div>
))

DisclaimerModal.displayName = "DisclaimerModal"

export default function Footer({
    disclaimer = DISCLAIMER,
    subtitle,
}: FooterProps) {
    const [showDisclaimer, setShowDisclaimer] = useState(false)

    const open = useCallback(() => setShowDisclaimer(true), [])
    const close = useCallback(() => setShowDisclaimer(false), [])

    return (
        <footer className="border-t bg-muted/50 px-6 py-3 flex items-center justify-between">
            <button
                onClick={open}
                className="text-xs text-muted-foreground hover:text-primary cursor-pointer hover:underline transition-colors font-medium"
            >
                Terms & Conditions
            </button>

            {subtitle ? (
                <div className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground/60">
                    {subtitle}
                </div>
            ) : (
                <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider font-semibold text-muted-foreground/60">
                    <span>Powered by</span>
                    <span className="text-primary/70">AI</span>
                </div>
            )}

            <AnimatePresence>
                {showDisclaimer && (
                    <DisclaimerModal disclaimer={disclaimer} onClose={close} />
                )}
            </AnimatePresence>
        </footer>
    )
}
